[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7.0"

data_models = { path = "../data_models", version = "0.1.0" }

[dev-dependencies]
rstest = "0.21.0"
beady = "0.6.1"